# Use Ctrl+a as the prefix key instead of Ctrl+b
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

# Set copy mode to vi schema
setw -g mode-keys vi

# Status bar colors
set -g status-style 'bg=#13161d fg=#8b949e'
set -g status-left-length 20
set -g status-right-length 50

# Status bar content
set -g status-left '#[fg=#00e68a,bold] #S #[fg=#30363d]│ '
set -g status-right '#[fg=#30363d]│#[fg=#8b949e] %H:%M #[fg=#30363d]│#[fg=#8b949e] %d-%b-%y '

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-style pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Put the status bar on the top
set -g status-position top

# More convenient and ergonomic window navigation
unbind n
unbind p
bind n next-window
bind b previous-window

# More convenient window splitting
unbind '%'
unbind '"'
unbind s
bind s split-window -v
bind v split-window -h

# Better copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection

# Killing panes and windows
unbind q
bind q kill-pane
bind -r Q kill-window

# Enable 24-bit color
set -as terminal-features ",alacritty*:RGB"
